sudo: required

language: go
go:
  - 1.7

services:
  - docker

before_deploy:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region ap-southeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars

# also trying to fix postgis bug
before_install:
 - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2

install: true

addons:
  postgresql: '9.4'
 
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb.sh
script:
- ./all.sh
notifications:
  hipchat:
    rooms:
      secure: "mv63qNPXrQ0baKG2ZOx4iePu4wS4HcXanOOlhyHjKcGdLCEb3m+ZkGY7LdZF7n61CG1Umg+lsWGSWFqHcOemSQ8SVwQUXCu/sP9pjAV9AuEmaKIR1J37ovZz7Cl2c29ejWECg2XM3WTu5lLRgIKXAaRr4d+sFpm097LH0IrtWNz1GFnIbJs43994wRrqJDOLKnf4sEpLRUCXwwQFN7N85KtR+VlxUx197kRBFpUKICX6S4psbbaJBGIzlqSa5ILrx6zmgJaKdHAw1RjMqRpWJESobjPmFk9S+Ecxlohk6GXCCd5ddHHY9LdWm3eirN8R5KQx9zuk1MfacDslFqaYK5ptCbK9LvkVB0mMn2ezuMlnvZobPeDdmKbtSqj+mJoY47OBFvSdO5bIOSErNRKzuxN9Jp9A4MS/znZCngUmy7VFESIq+LxZe4fvevPYFotLi/gB9TcbkCR0CU4ZBqb18AirIgos8b4lytsM/ADl2HD+mQpsjHKv7jAd4RoqiG9w6/i4GIC2w4mabaPcMvkU+t9sKUUOxrcMik7xwiKa5q67u8FVBWts5dg/aFgYRE0AKysYOBlJWxX3g3nD5wPK6E5GmlWSEftWiseXXiGOB+cQ+h6S5irV22aAAMkjV2TU8nNCrLD76MK1kGKxAt34uoYFSiwHpUXAeQAxk68/Pns="
    notify: true
    on_success: always
    on_failure: always

deploy:
   - provider: script
     skip_cleanup: true
     script: ./build-push.sh mtr-api mtr-ui
     on: 
       branch: master
  
env:
    global:
        - secure: "Kglouv0hLBTIAv3M3TEt3uhATvPVOZI/VmDZeyzBO0SndGpSI6D5CRmlv9WGRjpnJnMx7Fm385GvcAQvdfr3OOFzEwCBqjaFQJnUIiXYAhwHf2K3AJ8sEW2iBkRM648w797yNAYhZ705ahelq3ZrLJPW2NpGErKNlK/uxTzO1UcS5Xs2rhuu48XCgPgLTA7C3U903tvAwXueK2E9IJTBNXVidYG1T4cq1Pwa6cmCISzat/YSbAdavR11t28B4xPCThYCiGGi8hTzNQOktbyCK8cRqzt9+Gcxg919EaGywn+Rony1AAlGqn+BK5QCXgXJqTclxZYt/aIE1L46OO3ZMe1xqfZxKyTzXXWXRKTp6qYxWuKTs/rCwvww1Bt5Xz4t048d7FqhVTgx9lz7XtCiOC9bPx3gG37Dby72UEfxXa0wqqzwyJbr4cUcypa3D6QbVv6iTMEvxlM81SHvkTj2z+pLdLl1XeZb+orjdUG/mOEvzQH7tr/7B4qBbgXpktH9lgvEwMnArH5UQABk+J4PTRBFmZ7SBdrk3LyIAN3f7Cg3EJKQp5jLYPP7X0iaBD3GzFzQhXGDL/mntjzy5zCLxVILTyl01B+205A3uSIAUtWUrLMviBgdrmKci0L4BrRHeFuMrj7LYlQ0ZOQvOw3E3AXSGU7I08mkp888JBgUkB4="
        - secure: "oTFd0+fMR7HJ6gSAbXYMzciFxhrIaQdSeN4LgnR4jOO5QrupfqBEI2T3gqVDP3PvD3sjDCyktHxlZ+7ouELKHpaYgtFdTxcem7cWG1KoXbYTKIlhh4dORKuDcmO1GcCQbofnokB2QvU4oV+GCdG5kdNcy8f6vqTwNM2iHv4Uuq1W/t5iuV/KWbghiGo/ydTzfwpVjcEclsgXdyS6r3eQzwLVXSA0bAP9VEyEYPbsDO55hK+MPQ0UQN73+VYY4+u4Fc7E+rYpM5vqqAWHVys9QsTXfA3Jl6hC6yAoKhHXV/soavdb6pfdPHnj83xZQXOMRoAy1jI9MGyLXFUxuh7BwAnSjk8MA05VqKXOs3fvQlJ7iosdqsdTnYLrJfyir+cUUYvY2sVOPln2cveFBwvlK9fyzK5MH7yb3GSJuoW2UrSFG1yn2RoIKHG95stUCOBNScL2TjwxVSAZS5B+m+KNC2ZE64Vniuf9LuGb1ur9Z4jDr7OHHL0oczXuqsP5seRAqslhy2iN1RPBayH/2XzVjpT65+CDHzk6SL9tLWexB6GPcrpX1SzuNt0+riwCaY0Ve6awa+zqnnpT8gsK6rKeny+t1FPtLxnpRRmkWLZtzEPmnFqAlHinJEmAserAUi7LStnqyfNg6dTVhZroK+3NsGzj4U90dgRO5b4dNCES38s="
