sudo: required

language: go
go:
  - 1.6.1

services:
  - docker

before_deploy:
  - docker login --email="." --username="geonet+dockerbuild" --password="$docker_password" quay.io

# also trying to fix postgis bug
before_install:
 - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.2

install: true

addons:
  postgresql: '9.4'
 
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb.sh
script:
- export $(cat mtr-api/env.list | grep = | xargs) && go test ./mtr-api  -v
- export $(cat mtr-ui/env.list  | grep = | xargs) && go test ./mtr-ui  -v
notifications:
  hipchat:
    rooms:
      secure: "mv63qNPXrQ0baKG2ZOx4iePu4wS4HcXanOOlhyHjKcGdLCEb3m+ZkGY7LdZF7n61CG1Umg+lsWGSWFqHcOemSQ8SVwQUXCu/sP9pjAV9AuEmaKIR1J37ovZz7Cl2c29ejWECg2XM3WTu5lLRgIKXAaRr4d+sFpm097LH0IrtWNz1GFnIbJs43994wRrqJDOLKnf4sEpLRUCXwwQFN7N85KtR+VlxUx197kRBFpUKICX6S4psbbaJBGIzlqSa5ILrx6zmgJaKdHAw1RjMqRpWJESobjPmFk9S+Ecxlohk6GXCCd5ddHHY9LdWm3eirN8R5KQx9zuk1MfacDslFqaYK5ptCbK9LvkVB0mMn2ezuMlnvZobPeDdmKbtSqj+mJoY47OBFvSdO5bIOSErNRKzuxN9Jp9A4MS/znZCngUmy7VFESIq+LxZe4fvevPYFotLi/gB9TcbkCR0CU4ZBqb18AirIgos8b4lytsM/ADl2HD+mQpsjHKv7jAd4RoqiG9w6/i4GIC2w4mabaPcMvkU+t9sKUUOxrcMik7xwiKa5q67u8FVBWts5dg/aFgYRE0AKysYOBlJWxX3g3nD5wPK6E5GmlWSEftWiseXXiGOB+cQ+h6S5irV22aAAMkjV2TU8nNCrLD76MK1kGKxAt34uoYFSiwHpUXAeQAxk68/Pns="
    notify: true
    on_success: always
    on_failure: always

deploy:
   - provider: script
     skip_cleanup: true
     script: ./build-push.sh mtr-api mtr-ui
     on: 
       branch: master
  
env:
    global:
        - secure: "EcXIys90oK49nM8ImtxORtU3PdhuJWg3LijCcAm3Kr/v5LvYZ8aBavRGh15/e1cryFyMG237C0MPDqrKsGex4UOW9JkN/v9sLR7YnM9jjB6ZbEnGkNj6PrKcGPS7wKeBP/BA5DlozpYiD1qt5AJ1pCgibz9VBQ8CaDbuXJHeUUoqjgUitoNqyGLEgRqAhGnR+WtJP0TA2FCVtgPyJtaYDqtaeCpI8GmQcFs99zflTVXshrdjkV5LSYOfwyeAUezuL+23VQz1mQ99Dkgm2SH17UJjTeXeH/CWLttppJNIf8dum2QkIxKiakeB413Ph6Ksu/u2XJEpW+q+iOtQLWnX42o2TpLpNZJGS/ZsV65ooieG4FhZMOkU2Cjw77N3cuwkoYUtdef6DFK1FOATp0GU8eBSjGh5tjlmWkL+gsrx8c182CT1N2RCtQ9Vq1+tY6dYSXfldu0HB6qc0JVr9gS/1Ey9qakXYN8b5RRlMsz0ce6DOvph7/YipbyyRrYoF3nGfb3HNcwMNEzfJ6pyDHaG+ocwgl7R8/RMhYzAxEEivKy1AILOvHz/f3ZSDlr2pnoZ57XvJZd1XlgpAWOeyJQAt57sY6fPZy7NnztT++g+i9f+E7FzQO78MhKVoyD42vd9HJTpFzF7eQBGX24w+DhHEnlQjkdr9l5BP4NtMiH9toI="
